name: Windows RDP + Tailscale (with TUN Fix)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  setup-rdp:
    runs-on: ubuntu-22.04         # stabil, kompatibel dengan Docker & TUN
    container:
      image: ubuntu:22.04
      options: --privileged --cap-add=NET_ADMIN --device=/dev/net/tun

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl iptables sudo

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          mkdir -p /run/tailscale
          nohup tailscaled --state=mem: --socket=/run/tailscale/tailscaled.sock &
          sleep 3

      - name: Connect Tailscale
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          tailscale up --authkey="${TS_AUTHKEY}" --hostname="github-runner" --accept-dns=false
          tailscale status

      - name: Start Windows container (Dockur)
        run: |
          apt-get install -y docker.io qemu-system-x86
          docker run -d --name win11 \
            --privileged \
            -e VERSION=11 \
            -e RAM_SIZE=8G \
            -e CPU_CORES=4 \
            -p 3389:3389 \
            dockurr/windows
          sleep 60

      - name: Show RDP info
        run: |
          echo "Connect via Tailscale IP below:"
          tailscale ip -4

      - name: Keep alive for remote access
        run: sleep 3600
