name: Windows 11 RDP + Tailscale (Fixed for Ubuntu 24)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  setup-rdp:
    runs-on: ubuntu-22.04   # Ganti 24.04 ke 22.04 agar stabil (hindari konflik)
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get install -y --no-install-recommends \
            qemu-system-x86 curl unzip apt-transport-https ca-certificates gnupg lsb-release

      - name: Install Docker CE cleanly
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
            | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin

      - name: Start Windows container
        run: |
          sudo docker run -d --name win11 \
            --privileged \
            -e VERSION=11 \
            -e RAM_SIZE=8G \
            -e CPU_CORES=4 \
            -p 3389:3389 \
            --device /dev/kvm \
            dockurr/windows
          sleep 60
          sudo docker logs win11

      - name: Install and connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:codespace-rdp

      - name: Show RDP info
        run: |
          echo "Connect to this RDP via Tailscale IP:"
          tailscale ip -4

      - name: Keep alive for remote access
        run: sleep 3600
