name: "Windows RDP + Tailscale Codespace (Ubuntu 22.04)"

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest       # Gunakan runner resmi

    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove containerd conflict and update
        run: |
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get update

      - name: Install Docker from official repo (no containerd.io)
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli

      - name: Install supporting tools
        run: sudo apt-get install -y socat qemu-system-x86 curl unzip

      - name: Start Windows VM container
        run: |
          sudo docker pull dockurr/windows:latest
          sudo docker rm -f win11 || true
          sudo docker run -d --name win11 \
            --privileged \
            -e VERSION=11 \
            -e RAM_SIZE=6G \
            -e CPU_CORES=4 \
            -p 127.0.0.1:3389:3389 \
            dockurr/windows
          sleep 120   # Pastikan Windows VM siap menerima koneksi

      - name: Install Tailscale and start daemon
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo bash
